name: Build

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

env:
  CI: true
  FORCE_COLOR: true
  DOCKER_BUILDKIT: 1
  BUILDKIT_INLINE_CACHE: 1
  IMG_NAME_TAG: ghcr.io/${{ github.actor }}/lua5.1:latest

concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://${{ env.IMG_NAME_TAG }}
    steps:
    - uses: actions/checkout@v3
    - name: Hadolint GitHub action, A Dockerfile linting tool
      uses: hadolint/hadolint-action@v3.0.0
      with:
        config: lua/5.1/.hadolint.yml
        dockerfile: lua/5.1/Dockerfile
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Extract metadata (tags, labels) from Git reference and GitHub events for Docker
      uses: docker/metadata-action@v4
      id: meta
      with:
        images: ghcr.io/${{ github.actor }}/lua5.1
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flavor: latest=true
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
    - name: Build to ghcr cst validation
      uses: docker/build-push-action@v4
      with:
        push: false
        load: true
        context: lua/5.1
        file: lua/5.1/Dockerfile
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    - name: Scan your Docker container image for vulnerabilities
      uses: aquasecurity/trivy-action@master
      continue-on-error: true
      with:
        image-ref: ${{ env.IMG_NAME_TAG }}
        format: sarif
        exit-code: 1
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'MEDIUM,HIGH,CRITICAL'
        output: trivy-results.sarif
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: trivy-results.sarif
    - name: Run Container Structure Test
      uses: docker://gcr.io/gcp-runtimes/container-structure-test:latest
      with:
        args: test -v debug --force --output junit --test-report cst_junit_report.xml --config lua/5.1/config-cst.yml --image ${{ env.IMG_NAME_TAG }}
    - name: Upload CST Report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: cst_junit_report.xml
    - name: Display CST Report
      uses: mikepenz/action-junit-report@v3
      if: always()
      with:
        report_paths: cst_junit_report.xml
        github_token: ${{ secrets.GITHUB_TOKEN }}
