name: Publish

on:
  release:
    types:
      - published

env:
  CI: true
  FORCE_COLOR: true
  DOCKER_BUILDKIT: 1
  BUILDKIT_INLINE_CACHE: 1

concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}

defaults:
  run:
    shell: bash

jobs:
  docker:
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://hub.docker.com/repository/docker/${{ github.actor }}/lua5.1:latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Extract metadata (tags, labels) from Git reference and GitHub events for Docker
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: ${{ github.actor }}/lua5.1
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flavor: latest=true
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
      - name: Login at DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v4
        with:
          push: true
          context: lua/5.1
          file: lua/5.1/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  ghcr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v2
    - name: Extract metadata (tags, labels) from Git reference and GitHub events for Docker
      uses: docker/metadata-action@v4
      id: meta
      with:
        images: ghcr.io/${{ github.actor }}/lua5.1
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flavor: latest=true
        tags: type=semver,pattern={{version}}
    - name: Login at ghcr
      uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push to ghcr
      uses: docker/build-push-action@v4
      with:
        push: true
        context: lua/5.1
        file: lua/5.1/Dockerfile
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
